# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test Rcpp function
#'
#'
#' @param test test parameter
#'
#' @export
c_test <- function(test) {
    .Call(`_optMTP_c_test`, test)
}

#' Multiple testing following the graph
#'
#' @param alpha vector of the original alphas
#' @param G     transition matrix G
#' @param p_values  vector of p-values for the elementary hypothesis
#' @param log   TRUE: print log at each step; FALSE: silent
#'
#' @return Hypothesis rejection status indicator vector
#'
#' @export
c_mtp <- function(p_values, alpha, G, log = FALSE) {
    .Call(`_optMTP_c_mtp`, p_values, alpha, G, log)
}

