# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test Rcpp function
#'
#'
#' @param test test parameter
#'
#' @export
c_test <- function(test) {
    .Call('_optMTP_c_test', PACKAGE = 'optMTP', test)
}

#' Multiple testing following the graph
#'
#'
#' @param alpha original alpha vector
#' @param G     transition matrix G
#' @param p_values  p-values for the elementary hypothesis
#'
#' @return Hypothesis rejection status indicator vector
#'
#' @export
c_mtp <- function(p_values, alpha, G, log = FALSE) {
    .Call('_optMTP_c_mtp', PACKAGE = 'optMTP', p_values, alpha, G, log)
}

